name: CI

on: [push]

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    name: CWTools test
    steps:
    - name: CWTools test
      uses: Yard1/CWTools-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
